// @see https://stylelint.io/user-guide/rules/
module.exports = {
  extends: [
    'stylelint-config-standard-scss',
    'stylelint-config-recess-order',
  ],
  plugins: ['stylelint-order'],
  rules: {
    // SCSS 相关
    'scss/at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: ['tailwind', 'apply', 'layer', 'responsive', 'variants', 'screen'],
      },
    ],
    // 格式化相关
    'value-list-comma-space-after': 'always-single-line',
    'declaration-block-trailing-semicolon': 'always',
    'block-opening-brace-space-before': 'always',
    'selector-list-comma-space-before': 'always',
    // 缩进
    'indentation': 2,
    // 引号
    'string-quotes': 'single',
    // 属性顺序使用 recess-order
    'order/properties-order': [
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'display',
      'flex',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'flex-direction',
      'flex-wrap',
      'justify-content',
      'align-items',
      'align-content',
      'gap',
      'grid',
      'grid-template-columns',
      'grid-template-rows',
      'grid-area',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'border',
      'border-width',
      'border-style',
      'border-color',
      'border-radius',
      'background',
      'background-color',
      'background-image',
      'background-size',
      'background-position',
      'background-repeat',
      'color',
      'font',
      'font-size',
      'font-weight',
      'font-family',
      'font-style',
      'line-height',
      'text-align',
      'text-decoration',
      'text-indent',
      'white-space',
      'overflow',
      'opacity',
      'visibility',
      'transform',
      'transition',
      'animation',
      'box-shadow',
      'cursor',
      'pointer-events',
    ],
  },
  overrides: [
    {
      files: ['**/*.vue'],
      customSyntax: 'postcss-html',
    },
  ],
}
